services:
  - type: web
    name: academic-report-system
    env: docker
    plan: free
    region: oregon
    dockerContext: .
    dockerfilePath: Dockerfile
    envVars:
      - key: PORT
        value: 10000
